# 服务内配置
wls:
  swagger:
    enabled: true
    groupName: "wls-system-api"
    basePackage: "cn.erectpine"
    title: "系统服务接口文档"
    description: "调用接口前请详细阅读文档，并遵守文档调用规范"
    version: "1.0.0"
    contact-name: "wls"
    contact-url: "erectpine.cn"
    contact-email: "1626961806@qq.com"

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9003
  servlet:
    # 应用的访问路径
    context-path: /wls-system

# Spring配置
spring:
  datasource:
    url: jdbc:mysql://159.75.93.83:3306/wls-ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: wls-mysql-tencent
