#pulsar:
#  allow-interceptor: false
#  auto-start: true
#  connection-timeout-sec: 10
##  consumer:
##    default:
##      ack-timeout-ms: 3000
##      dead-letter-policy-max-redeliver-count: -1
#  consumer-name-delimiter: ''
#  enable-tcp-no-delay: false
#  io-threads: 10
#  keep-alive-interval-sec: 20
#  listener-threads: 10
#  namespace: default
#  operation-timeout-sec: 10
##  service-url: pulsar://localhost:6650
#  starting-backoff-interval-ms: 10
#  max-backoff-interval-sec: 20
#  tenant: public
