server:
  port: 9000

spring:
  application:
    # 应用名称
    name: wls-gateway
  cloud:
    nacos:
      discovery:
        # 命名空间
        namespace: c49938e7-209f-499c-8b24-ef4c746b90a5
        # 服务注册地址
        server-addr: 123.57.101.219:8848
    gateway:
      routes:
        # 系统服务
        - id: wls-system
          uri: lb://wls-system
          predicates:
            - Path=/wls-system/**
          filters:
            - StripPrefix=1
        # 数据字典服务
        - id: wls-dict
          uri: lb://wls-dict
          predicates:
            - Path=/wls-dict/**
          filters:
            - StripPrefix=1


