server:
  port: 9000

spring:
  application:
    # 应用名称
    name: wls-gateway
  cloud:
    nacos:
      discovery:
        # 命名空间
        namespace: fdd50687827f43de9f4cee4c0d72876c
        # 服务注册地址
        server-addr: https://nacos.wls.plus
    gateway:
      routes:
        # 系统服务
        - id: wls-system
          uri: lb://wls-system
          predicates:
            - Path=/wls-system/**
          filters:
            - StripPrefix=1
        # 数据字典服务
        - id: wls-dict
          uri: lb://wls-dict
          predicates:
            - Path=/wls-dict/**
          filters:
            - StripPrefix=1


