### 角色列表
POST http://{{host}}/role/list
Content-Type: application/json
Authorization: token
single: qqqmmm

{
  "current": "1",
  "size": 2
}

### 根据ID获取角色
GET http://{{host}}/role/3

### 添加角色
POST http://{{host}}/role
Content-Type: application/json

{
  "roleKey": "list"
}

### 根据ID修改角色
PUT http://{{host}}/role

### 根据ID删除角色
DELETE http://{{host}}/role/{{id}}