### 分页列表
GET http://{{host}}/user/list?userName=wls&email=1626

### 根据id获取用户信息详情
GET http://{{host}}/user/1


### 新增-用户信息
POST http://{{host}}/user
Content-Type: application/json

{
  "userName": "",
  "sex": 1,
  "nickName": "wls2"
}

### 修改-用户信息
PUT http://{{host}}/user
Content-Type: application/json

{
  "userName": "",
  "userId": ""
}

### 删除-用户信息
DELETE http://{{host}}/user/100
Content-Type: application/json

{
  "userName": "wlss",
  "userId": "50"
}






