### 分页列表
POST http://{{host}}/user/list
Content-Type: application/json

{
  "current": "1",
  "size": 2,
  "userName": "wls",
  "orders": [
    {
      "column": "create_time",
      "asc": true
    }
  ]
}

### 根据id获取用户信息详情
GET http://{{host}}/user/1


### 新增-用户信息
POST http://{{host}}/user
Content-Type: application/json

{
  "userName": "wls2",
  "sex": 1,
  "nickName": "wls2"
}

### 修改-用户信息
PUT http://{{host}}/user
Content-Type: application/json

{
  "userName": "wlss",
  "userId": "50"
}

### 删除-用户信息
DELETE http://{{host}}/user/100
Content-Type: application/json

{
  "userName": "wlss",
  "userId": "50"
}




