# 项目相关配置
wls:
  # 服务名
  serviceName: ${spring.application.name}
  # 启动环境
  active: ${spring.profiles.active}

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9001
  servlet:
    # 应用的访问路径
    context-path: /gencode

# Spring配置
spring:
  profiles:
    active: dev
  application:
    name: wls-gencode
  # json中忽略null属性值
  jackson:
    parser:
      allow-numeric-leading-zeros: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true



